--return {
--  {
--    "mason-org/mason.nvim",
--    opts = {
--      ensure_installed = { "vsg" },
--    },
--  },
--
--  {
--    "stevearc/conform.nvim",
--    optional = true,
--    opts = function(_, opts)
--      opts.formatters_by_ft = opts.formatters_by_ft or {}
--      opts.formatters_by_ft.vhdl = { "vsg" }
--
--      opts.formatters = opts.formatters or {}
--      opts.formatters.vsg = {
--        command = "vsg",
--        args = function(_, ctx)
--          local root = vim.fs.root(ctx.dirname, { "vsg_config.yaml", ".vsg.yaml", ".git" }) or vim.fn.getcwd()
--          local config = nil
--
--          if vim.fn.filereadable(root .. "/vsg_config.yaml") == 1 then
--            config = root .. "/vsg_config.yaml"
--          elseif vim.fn.filereadable(root .. "/.vsg.yaml") == 1 then
--            config = root .. "/.vsg.yaml"
--          end
--
--          local args = {}
--          if config then
--            vim.list_extend(args, { "--configuration", config })
--          end
--
--          vim.list_extend(args, {
--            "-f",
--            ctx.filename,
--            "--fix",
--          })
--
--          return args
--        end,
--        stdin = false,
--        exit_codes = { 0, 1 },
--      }
--    end,
--  },
--
--  {
--    "mfussenegger/nvim-lint",
--    optional = true,
--    config = function(_, opts)
--      local lint = require("lint")
--
--      lint.linters_by_ft = vim.tbl_deep_extend("force", lint.linters_by_ft or {}, {
--        vhdl = { "vsg" },
--      })
--
--      lint.linters.vsg = function()
--        local file = vim.api.nvim_buf_get_name(0)
--        local dir = vim.fs.dirname(file)
--        local root = vim.fs.root(dir, { "vsg_config.yaml", ".vsg.yaml", ".git" }) or vim.fn.getcwd()
--        local config = nil
--
--        if vim.fn.filereadable(root .. "/vsg_config.yaml") == 1 then
--          config = root .. "/vsg_config.yaml"
--        elseif vim.fn.filereadable(root .. "/.vsg.yaml") == 1 then
--          config = root .. "/.vsg.yaml"
--        end
--
--        local args = {}
--        if config then
--          vim.list_extend(args, { "--configuration", config })
--        end
--
--        vim.list_extend(args, {
--          "-f",
--          file,
--          "--output_format",
--          "syntastic",
--        })
--
--        return {
--          cmd = "vsg",
--          stdin = false,
--          append_fname = false,
--          args = args,
--          ignore_exitcode = true,
--          parser = require("lint.parser").from_errorformat("%tRROR: %f(%l)%*[^(] -- %m,%tARNING: %f(%l)%*[^(] -- %m", {
--            source = "vsg",
--            severity = {
--              E = vim.diagnostic.severity.ERROR,
--              W = vim.diagnostic.severity.WARN,
--            },
--          }),
--        }
--      end
--
--      vim.api.nvim_create_autocmd({ "BufReadPost", "BufWritePost", "InsertLeave" }, {
--        callback = function()
--          lint.try_lint("vsg")
--        end,
--      })
--    end,
--  },
--}
